---
- hosts: all
  become: true
  tasks:
  - name: apt upgrade
    apt:
      update_cache: true
      upgrade: full
  - name: apt install
    apt:
      update_cache: true
      name:
        - jq
        - wget
        - python3
        - python3-dev
        - python3-pip
        - python3-venv
        - build-essential
        - libssl-dev
        - libffi-dev

  # Install Docker
  - name: Add docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  - name: Install packages for docker
    apt:
      state: present
      update_cache: true
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - lsb-release
  - name: Add docker apt repository
    apt_repository:
      update_cache: true
      # yamllint disable rule:line-length
      repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      # yamllint enable rule:line-length
  - name: Install docker packages
    apt:
      update_cache: true
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  - name: Add user to docker group
    user:
      name: "{{ ansible_env.USER }}"
      groups: docker
      append: true
  - name: Ensure docker service is enabled
    systemd:
      name: docker
      state: started
      enabled: true
  - name: Install docker-compose
    get_url:
      # yamllint disable rule:line-length
      url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
      # yamllint enable rule:line-length
      dest: /usr/local/bin/docker-compose
      mode: +x

  # Install google-cloud-sdk (gcloud)
  - name: apt install packages for gcloud
    apt:
      update_cache: true
      name:
        - unzip
        - xvfb
        - libxi6
        - libgconf-2-4
        - default-jdk
  - name: Add gcloud GPG key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - name: Add gcloud apt repository
    apt_repository:
      update_cache: true
      # yamllint disable rule:line-length
      repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
      # yamllint enable rule:line-length
  - name: Install gcloud packages
    apt:
      update_cache: true
      name:
        - google-cloud-sdk

  # Cleanup
  - name: apt autoremove
    apt:
      purge: true
      autoremove: true
