# -*- mode: ruby -*-
# vi: set ft=ruby :

Dotenv.load

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.disk :disk, size: "#{ENV['VB_DISK_SIZE']}", primary: true
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of cpus and memory on the VM:
    vb.cpus = "#{ENV['VB_CPUS']}".to_i
    vb.memory = "#{ENV['VB_MEMORY']}".to_i

    # Fix https://www.virtualbox.org/ticket/15705
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  config.vm.provision :root_user, type: "shell", path: "provision_root.sh"
  config.vm.provision :vagrant_user, type: "shell", privileged: false, path: "provision_nonroot.sh"

  config.vm.provision :vagrant_user_runner, type: "shell", privileged: false, inline: <<-SHELL
    # Install actions/runner
    mkdir ~/actions-runner && cd ~/actions-runner
    GHA_RUNNER_VERSION="2.285.0"
    curl -so actions-runner-linux-x64-${GHA_RUNNER_VERSION}.tar.gz -L https://github.com/actions/runner/releases/download/v${GHA_RUNNER_VERSION}/actions-runner-linux-x64-${GHA_RUNNER_VERSION}.tar.gz
    echo "87e4f032839466086dc7828f2e044bfd8fff33d57a009a2df7a03c163ac0f87b  actions-runner-linux-x64-${GHA_RUNNER_VERSION}.tar.gz" | shasum -a 256 -c
    tar xzf ./actions-runner-linux-x64-${GHA_RUNNER_VERSION}.tar.gz
    # ./config.sh --url #{ENV['GHA_RUNNER_URL']} --token #{ENV['GHA_RUNNER_TOKEN']}
    # nohup ./run.sh &
  SHELL
end
